In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Carrega amostra local para exploracao inicial
df = pd.read_csv('/Users/gustavosoares/Documents/Pos Tech/tech_challeng/tech_challeng_2/data/raw/inep/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_brasil.csv')
df.head()

,ano,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao
0,2025,Pública,66.0,60.0,64.00,67.00,71.00,74.00,77.00,80,88.00
1,2024,Pública,59.2,59.9,63.77,67.47,70.97,74.23,77.24,80,87.37
2,2023,Pública,55.9,59.9,63.77,67.47,70.97,74.23,77.24,80,86.00

In [8]:
nulos = pd.DataFrame({
    "nulos": df.isna().sum(),
    "total": len(df),
    "pct_nulos": (df.isna().mean() * 100).round(2)
}).sort_values("pct_nulos", ascending=False)

nulos

                         nulos  total  pct_nulos
ano                          0      3        0.0
rede                         0      3        0.0
taxa_alfabetizacao           0      3        0.0
meta_alfabetizacao_2024      0      3        0.0
meta_alfabetizacao_2025      0      3        0.0
meta_alfabetizacao_2026      0      3        0.0
meta_alfabetizacao_2027      0      3        0.0
meta_alfabetizacao_2028      0      3        0.0
meta_alfabetizacao_2029      0      3        0.0
meta_alfabetizacao_2030      0      3        0.0
percentual_participacao      0      3        0.0

In [6]:
print(df.nunique())

ano                        3
rede                       1
taxa_alfabetizacao         3
meta_alfabetizacao_2024    2
meta_alfabetizacao_2025    2
meta_alfabetizacao_2026    2
meta_alfabetizacao_2027    2
meta_alfabetizacao_2028    2
meta_alfabetizacao_2029    2
meta_alfabetizacao_2030    1
percentual_participacao    3
dtype: int64