In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Carrega amostra local para exploracao inicial
df = pd.read_csv('/Users/gustavosoares/Documents/Pos Tech/tech_challeng/tech_challeng_2/data/raw/inep/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_municipio.csv')
df.head()

,ano,id_municipio,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,nivel_alfabetizacao,percentual_participacao
0,2023,4301750,Municipal,NaN,NaN,14.05,23.65,37.00,52.68,67.85,80,NaN,NaN
1,2024,4301750,Municipal,4.40,NaN,14.05,23.65,37.00,52.68,67.85,80,0.0,92.59
2,2024,2406908,Municipal,42.86,7.94,14.05,23.65,37.00,52.68,67.85,80,1.0,84.00
3,2023,2406908,Municipal,4.40,7.94,14.05,23.65,37.00,52.68,67.85,80,0.0,82.14
4,2023,1718501,Municipal,4.60,8.25,14.48,24.16,37.49,53.03,68.00,80,0.0,95.65

In [2]:
nulos = pd.DataFrame({
    "nulos": df.isna().sum(),
    "total": len(df),
    "pct_nulos": (df.isna().mean() * 100).round(2)
}).sort_values("pct_nulos", ascending=False)

nulos

                         nulos  total  pct_nulos
meta_alfabetizacao_2024    240  10704       2.24
taxa_alfabetizacao         120  10704       1.12
nivel_alfabetizacao        120  10704       1.12
percentual_participacao    120  10704       1.12
ano                          0  10704       0.00
id_municipio                 0  10704       0.00
rede                         0  10704       0.00
meta_alfabetizacao_2025      0  10704       0.00
meta_alfabetizacao_2026      0  10704       0.00
meta_alfabetizacao_2027      0  10704       0.00
meta_alfabetizacao_2028      0  10704       0.00
meta_alfabetizacao_2029      0  10704       0.00
meta_alfabetizacao_2030      0  10704       0.00

In [6]:
print(df.nunique())

ano                        3
rede                       1
taxa_alfabetizacao         3
meta_alfabetizacao_2024    2
meta_alfabetizacao_2025    2
meta_alfabetizacao_2026    2
meta_alfabetizacao_2027    2
meta_alfabetizacao_2028    2
meta_alfabetizacao_2029    2
meta_alfabetizacao_2030    1
percentual_participacao    3
dtype: int64